/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        xs: '480px',
      },
      colors: {
        'surface': '#f8f9fb',
        'surface-dim': '#d9dadc',
        'surface-bright': '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f6',
        'surface-container': '#edeef0',
        'surface-container-high': '#e7e8ea',
        'surface-container-highest': '#e1e2e4',
        'on-surface': '#191c1e',
        'on-surface-variant': '#444934',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f3',
        'outline': '#747962',
        'outline-variant': '#c4c9ae',
        'surface-tint': '#506600',
        'primary': '#506600',
        'on-primary': '#ffffff',
        'primary-container': '#c6f432',
        'on-primary-container': '#566d00',
        'inverse-primary': '#aad600',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        'tertiary': '#494bd6',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e2e0ff',
        'on-tertiary-container': '#5052dd',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c5f331',
        'primary-fixed-dim': '#aad600',
        'on-primary-fixed': '#161f00',
        'on-primary-fixed-variant': '#3b4d00',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'background': '#f8f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e1e2e4',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px' }],
        'headline-md': ['20px', { lineHeight: '28px' }],
        'stat-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em' }],
      },
      spacing: {
        'gutter': '24px',
        'card-padding': '24px',
        'unit': '4px',
        'margin': '32px',
      },
      borderRadius: {
        'card': '1.5rem',
        'pill': '9999px',
      },
      boxShadow: {
        'glass': '0 12px 40px rgba(0, 0, 0, 0.04)',
        'nav': '20px 0 40px rgba(0, 0, 0, 0.02)',
      },
    },
  },
  plugins: [],
}
